./src/encdec-gpu \
--cnn-mem 1800m \
--path_dev_src=$HOME/tmp.1000.en \
--path_dev_trg=$HOME/tmp.1000.en \
--path_dict_src=$HOME/tmp.d_src \
--path_dict_trg=$HOME/tmp.d_trg \
--path_model=$HOME/tmp.model \
--path_test_src=$HOME/tmp.1000.en \
--path_test_out=$HOME/tmp.test_out \
--path_train_src=$HOME/tmp.1000.en \
--path_train_trg=$HOME/tmp.1000.en \
--dim-attention 32 \
--dim-hidden 32 \
--dim-input 32 \
--batch-size 80 \
--builder 1 \
--depth-layer 1 \
--eta 0.001
